/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryManDirectory;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author nemod
 */
public class ManageOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrdersJPanel
     */
    JPanel userProcessContainer;
    Restaurant restaurant;
    UserAccount userAccount;
    Order order;
    DeliveryManDirectory deliveryManDirectory;
    public ManageOrdersJPanel(JPanel userProcessContainer, Restaurant restaurant, DeliveryManDirectory deliveryManDirectory, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.restaurant = restaurant;
        this.deliveryManDirectory = deliveryManDirectory;
        this.userAccount = userAccount;
        btnAssign.setEnabled(false);
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateTable()
    {
        if(this.restaurant.getWorkQueue().getWorkRequestList() != null)
        {
            DefaultTableModel dtm = (DefaultTableModel) restaurantOrdersTable.getModel();
            dtm.setRowCount(0);
            for (WorkRequest w : this.restaurant.getWorkQueue().getWorkRequestList()) 
            {
                if(w.getOrder() != null)
                {
                    Object row[] = new Object[7];
                    row[0] = w.getOrder().getOrderId();
                    Iterator itr = w.getOrder().getOrderMap().entrySet().iterator();
                    StringBuilder sb = new StringBuilder("");
                    while (itr.hasNext()) 
                    { 
                        Map.Entry mapElement = (Map.Entry)itr.next(); 
                        sb.append(mapElement.getKey()+", ");
                    } 
                    row[1]= sb;
                    row[2] = w.getReceiver().getCustomer().getName();
                    row[3] = w.getOrder().getComment();
                    
                    if(w.getSender().getCustomer() == null)
                    {
                       row[4] = this.restaurant.getName();
                    }
                    else
                    {
                        row[4] = w.getSender().getCustomer().getName(); 
                    }
                    row[5] = w.getOrder().getDeliveryAddress();
                    row[6] = w.getStatus();
                    dtm.addRow(row);
                }
  
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        restaurantOrdersTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAcceptOrder = new javax.swing.JButton();
        btnDeclineOrder = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(32, 47, 90));

        restaurantOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order Id", "Ordered Items", "Customer Name", "Message", "Sender", "Customer Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(restaurantOrdersTable);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Order Details");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnAcceptOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnAcceptOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAcceptOrder.setText("Accept Order");
        btnAcceptOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptOrderActionPerformed(evt);
            }
        });

        btnDeclineOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnDeclineOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeclineOrder.setText("Decline Order");
        btnDeclineOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineOrderActionPerformed(evt);
            }
        });

        btnAssign.setBackground(new java.awt.Color(255, 255, 255));
        btnAssign.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAssign.setText("Assign to DeliveryMan");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcceptOrder)
                        .addGap(63, 63, 63)
                        .addComponent(btnDeclineOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnAssign)
                        .addGap(89, 89, 89)
                        .addComponent(btnBack)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceptOrder)
                    .addComponent(btnDeclineOrder)
                    .addComponent(btnAssign)
                    .addComponent(btnBack))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptOrderActionPerformed
        // TODO add your handling code here:
        btnAssign.setEnabled(true);
        int selectedRow = restaurantOrdersTable.getSelectedRow();
        if(selectedRow >= 0)
        {
            String orderId= (String)restaurantOrdersTable.getValueAt(selectedRow, 0);
            for(WorkRequest wr: this.restaurant.getWorkQueue().getWorkRequestList())
            {
                if(wr.getOrder().getOrderId().equals(orderId))
                {
                  if(wr.getStatus().equalsIgnoreCase("Assinged to delivery Man"))
                   {
                        JOptionPane.showMessageDialog(null, "The order is already assigned for delivery");
                        break;
                   }
                  else if(wr.getStatus().equalsIgnoreCase("Decline"))
                  {
                      JOptionPane.showMessageDialog(null, "The order is already declined."); 
                      break;
                  }
                  else
                  {
                      if(wr.getStatus().equalsIgnoreCase("Accepted"))
                      {
                         JOptionPane.showMessageDialog(null, "The order is already accepted."); 
                        break; 
                      }
                      else
                      {
                          wr.setStatus("Accepted");
                          JOptionPane.showMessageDialog(null, "The order has been accepted.");
                          this.populateTable();
                          break;
                      }
                  }
                }
            }
        }
    }//GEN-LAST:event_btnAcceptOrderActionPerformed

    private void btnDeclineOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineOrderActionPerformed
        // TODO add your handling code here:
        btnAssign.setEnabled(false);
        int selectedRow = restaurantOrdersTable.getSelectedRow();
        if(selectedRow >= 0)
        {
           String orderId= (String)restaurantOrdersTable.getValueAt(selectedRow, 0);
            for(WorkRequest wr: this.restaurant.getWorkQueue().getWorkRequestList())
            {
                if(wr.getOrder().getOrderId().equals(orderId))
                {
                  wr.setStatus("Decline");
                  this.populateTable();
                  break;
                }
            }
        }
    }//GEN-LAST:event_btnDeclineOrderActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = restaurantOrdersTable.getSelectedRow();
        if(selectedRow >= 0)
        {
            String orderId= (String)restaurantOrdersTable.getValueAt(selectedRow, 0);
            for(WorkRequest wr: this.restaurant.getWorkQueue().getWorkRequestList())
            {
                if(wr.getOrder().getOrderId().equals(orderId))
                {
                    order = wr.getOrder();
                    break;
                }
            }
            AssignToDeliverymanJPanel assignPanel = new AssignToDeliverymanJPanel(userProcessContainer, order, this.deliveryManDirectory, this.restaurant, this.userAccount);
            userProcessContainer.add("assignPanel", assignPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a order to assign to delivery man.");
        }
        
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminWorkAreaJPanel adminPanel = (AdminWorkAreaJPanel) component;
//        adminPanel.postEvent(e);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptOrder;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeclineOrder;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable restaurantOrdersTable;
    // End of variables declaration//GEN-END:variables
}
